refactor: 멀티모듈 도입
nonsoolmate-official/nonsoolmate-server pull request #110
Opened 2024-09-11 11:11 UTC by mikekks

## 📝 PR 타입
- [ ] 기능 추가
- [ ] 기능 수정
- [ ] 기능 삭제
- [ ] 버그 수정
- [x] 기능 개선
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 📝 반영 브랜치

closed #109 

## 📝 변경 사항

- batch 시스템, 선생님 서버 등을 고려했을 때 중복도를 줄이고, 확장성있는 서버를 구축하고자 멀티모듈로 구현했습니다.
- 일부 기능 수정이 있었는데요! 커밋 단위로 보시면 편할 것 같습니다!
- 전체적인 패키지(폴더링)들의 위치가 변한 부분이 있습니다! 이 부분은 같이 회의하면서 의존성에 대해 얘기해보면 좋을 것 같습니다!

## 📝 테스트 결과

- 얼마 없지만 테스트 코드 돌려봤슴다... 
<img width="544" alt="스크린샷 2024-09-11 오후 8 03 45" src="https://github.com/user-attachments/assets/f2f9c1a7-0d4c-4e72-8a64-781b992b4781">

## 📝 To Reviewer

2024-09-13 07:53 UTC, sung-silver requested changes
의견 한번 주시면 감사하겠습니다! 그리고 저희가 각 모듈별로 도메인 이름은 유지하는 것 같아서 `nonsoolmate-domain` -> `nonsoolmate-storage`(or `nonsoolmate-db-core`) 이런식으로 변경하고 내부적으로는 도메인을 유지하는 건 어떠신지도 궁금합니다!

그리고 PR 헤더 [REFACTOR]로 부탁드립니다! 이슈도 같이 수정하면 좋을듯요 아니면 멀티모듈 구현에 따른 변경(기능 자체에 문제가 있진 않았음)이니까 [FEAT]으로 이슈랑 PR 모두 수정해도 좋을 것 같네요!

2024-09-13 07:53 UTC, sung-silver commented on nonsoolmate-api/src/main/java/com/nonsoolmate/global/config/QuerydslConfig.java
> +package com.nonsoolmate.global.config;
QueryDSL은 api보다 domain(entity, repository)에 넣는게 좋지 않을까요? queryDSL의 의존성도 domain에 존재하는데 어떻게 생각하시나요?

2024-09-13 07:53 UTC, sung-silver commented on nonsoolmate-api/src/main/java/com/nonsoolmate/auth/NaverAuthService.java
> +public class NaverAuthService extends AuthService {
요 파일은 Service 패키지에서 분리되어 나온 이유가 있을까요?

2024-09-14 01:03 UTC, mikekks commented on nonsoolmate-api/src/main/java/com/nonsoolmate/global/security/utils/RequestUtils.java
> +import com.nonsoolmate.response.SuccessResponse;
JwtValidator

2024-09-14 01:18 UTC, mikekks commented on nonsoolmate-api/src/main/java/com/nonsoolmate/global/security/utils/RequestUtils.java
> +import com.nonsoolmate.response.SuccessResponse;
이거는 머지 후에 작업해도 괜찮을까요??

2024-09-14 01:23 UTC, sung-silver commented on nonsoolmate-api/src/main/java/com/nonsoolmate/global/security/utils/RequestUtils.java
> +import com.nonsoolmate.response.SuccessResponse;
네넵!

2024-09-15 01:24 UTC, mikekks commented on nonsoolmate-api/src/main/java/com/nonsoolmate/global/config/QuerydslConfig.java
> +package com.nonsoolmate.global.config;
QueryProjections

2024-09-15 01:25 UTC, mikekks commented on nonsoolmate-external/src/main/java/com/nonsoolmate/auth/vo/enums/AuthType.java
> +public enum AuthType {
한 번 확인

2024-09-15 01:25 UTC, mikekks commented on nonsoolmate-domain/src/main/java/com/nonsoolmate/couponMember/repository/dto/CouponResponseDTO.java
> +public class CouponResponseDTO {
QueryProjection

2024-09-15 02:08 UTC, sung-silver approved these changes
변경해주셔서 감사합니다! 한 주동안 고생 많으셨습니도

2024-09-15 02:12 UTC, merged