feat: 빌링 자동 결제 구현
nonsoolmate-official/nonsoolmate-server pull request #179
Opened 2024-10-07 08:41 UTC by mikekks

## 📝 PR 타입
- [X] 기능 추가
- [ ] 기능 수정
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 📝 반영 브랜치

- feat/#167 -> dev
- closed #167 

## 📝 변경 사항

- 빌링 자동 결제를 구현했습니다.
- 기존 결제로직과 동일하게 가는게 관리하기 편할 것 같아서 최대한 비슷하게 진행했습니다.

## 📝 테스트 결과

## 📝 To Reviewer

- 테스트를 어떻게 하는게 좋을지 여쭤보고 싶습니다!

2024-10-07 08:55 UTC, sung-silver requested changes
PR 제목도 컨벤션에 맞추어 수정 부탁드립니다! 리뷰 남겼습니다 그리고 CI 실패인데 모듈 의존성을 한번 확인해봐야할 것 같아요!

2024-10-07 08:55 UTC, sung-silver commented on nonsoolmate-batch/src/main/java/com/nonsoolmate/payment/BillingScheduler.java
> +		orders.forEach(
order를 가져올때 membership 테이블에서 status가 Terminated가 아닌 Member로 조회하는 로직이 필요할 것 같습니다!

2024-10-07 08:55 UTC, sung-silver commented on nonsoolmate-batch/src/main/java/com/nonsoolmate/payment/BillingScheduler.java
> +					orderService.createOrder(order.getProduct(), NO_COUPON_MEMBER_ID, memberId);
각 회원마다 이런 로직이 수행되는데 동기로 처리되면 한명이 실패하면 그 실패한 뒤의 회원부터는 결제 요청이 안갈 것 같은데, 클래스 분리 및 메서드에 `@Asyn`c 적용해서 비동기 처리하여 병렬로 수행되게 하는건 어떠신가요?

각 함수에 대한 트랜잭션 처리도 한번 정리해서 고민해봐야겠네요..

2024-10-07 08:55 UTC, sung-silver commented on nonsoolmate-db-core/src/main/java/com/nonsoolmate/coupon/entity/Coupon.java
> +	}
결제 API에도 적용해야할 것 같네요 감사합니다!

2024-10-07 09:13 UTC, mikekks commented on nonsoolmate-batch/src/main/java/com/nonsoolmate/payment/BillingScheduler.java
> +		orders.forEach(
넵 수정했습니다!

2024-10-07 09:51 UTC, mikekks commented on nonsoolmate-batch/src/main/java/com/nonsoolmate/payment/BillingScheduler.java
> +					orderService.createOrder(order.getProduct(), NO_COUPON_MEMBER_ID, memberId);
좋은 생각인 것 같습니다! 적용했씁니다 !!

2024-10-07 12:31 UTC, sung-silver requested changes
확인이 늦어서 죄송합니다!

2024-10-07 12:31 UTC, sung-silver commented on nonsoolmate-db-core/src/main/java/com/nonsoolmate/order/entity/OrderDetail.java
> +	private Boolean isPayment;
혹시 boolean이 아니라 Boolean Wrapper 타입을 사용하신 이유가 있을까요?!

2024-10-07 12:31 UTC, sung-silver commented on nonsoolmate-batch/src/main/java/com/nonsoolmate/payment/BillingScheduler.java
> +	}
https://cano721.tistory.com/208

`@Async` 사용시 자가호출은 적용이 안된다고해서 다른 클래스로 빼는게 좋을 것 같습니다!
그리고 첫 결제에서도 적용되는 로직인데 하나의 함수로 만들어두고 같이 사용할 수 있는 방법은 없을지 얘기해보면 좋을 것 같습니다! 이부분은 오늘까지 마감사항에는 해당 아닐 것 같아서 이번주 내로 회의 한 번하는 것도 좋을 것 같네요!!

2024-10-07 12:31 UTC, sung-silver commented on nonsoolmate-batch/src/main/java/com/nonsoolmate/payment/BillingScheduler.java
> +			couponMember.updateIsUsed(true);
첫 결제시에 이부분 빠트린 것 같은데 수정해두겠습니다!

2024-10-07 14:36 UTC, mikekks commented on nonsoolmate-db-core/src/main/java/com/nonsoolmate/order/entity/OrderDetail.java
> +	private Boolean isPayment;
다른 엔티티에도 이렇게 사용된거 같아 추가해봤습니다!

2024-10-09 03:49 UTC, sung-silver commented on nonsoolmate-db-core/src/main/java/com/nonsoolmate/order/entity/OrderDetail.java
> +	private Boolean isPayment;
확인했습니다!

2024-10-09 03:50 UTC, sung-silver approved these changes
PR 범위가 너무 커질 것 같아서 이제 머지하고 공통된 로직 분리는 따로 빼는게 좋을 것 같습니다! 수고하셨습니다!

2024-10-09 04:42 UTC, merged