[CHORE] 질의 응답 링크 추가
nonsoolmate-official/nonsoolmate-server pull request #221
Opened 2024-10-20 05:51 UTC by mikekks

## 📝 PR 타입
- [ ] 기능 추가
- [x] 기능 수정
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## 📝 반영 브랜치

- chore/#220 -> dev
- closed #220 

## 📝 변경 사항

- 질의 응답 링크 추가했습니다.

## 📝 테스트 결과

<img width="833" alt="스크린샷 2024-10-20 오후 2 51 10" src="https://github.com/user-attachments/assets/19f84209-b490-42f5-9bc6-36801ab64e32">

## 📝 To Reviewer

2024-10-20 12:58 UTC, sung-silver requested changes
리뷰 한번 확인 부탁드립니다!

2024-10-20 12:58 UTC, sung-silver commented on nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/dto/response/TeacherResponseDTO.java
> +        teacher.getQnaLink(),
이게 프리미엄 회원일때에만 떠야할 것 같은데 service에서 if문으로 나누는건 어떨까요?

2024-10-22 02:00 UTC, mikekks commented on nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/dto/response/TeacherResponseDTO.java
> +        teacher.getQnaLink(),
아 넵 맞네요 추가하겠씁니다!

2024-10-22 02:20 UTC, mikekks commented on nonsoolmate-api/src/main/java/com/nonsoolmate/member/controller/dto/response/TeacherResponseDTO.java
> +        teacher.getQnaLink(),
수정했습니다!! 다시 한 번 리뷰해주시면 감사하겠슴다!!

2024-10-23 03:26 UTC, merged